# Generated by Django 3.2.25 on 2024-08-29 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_email_customer_message_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
